%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------

# ros package path
rospackage_path: "/home/wpr/code/catkin_ws/src/orbslam_semantic_nav_ros/" #ros包路径

# Camera calibration and distortion parameters (OpenCV) 
Camera.fx: 611.4509887695312
Camera.fy: 611.4857177734375
Camera.cx: 433.2039794921875
Camera.cy: 249.4730224609375

Camera.k1: 0
Camera.k2: 0
Camera.p1: 0
Camera.p2: 0
Camera.k3: 0

Camera.width: 640
Camera.height: 480

# Camera frames per second 
Camera.fps: 10.0

# IR projector baseline times fx (aprox.)
Camera.bf: 40.0

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

# Close/Far threshold. Baseline times.
ThDepth: 40.0

# Deptmap values factor 
DepthMapFactor: 1000.0

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 1000

# ORB Extractor: Scale factor between levels in the scale pyramid 	
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid	
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast			
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3
Viewer.ViewpointX: 0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -1.8
Viewer.ViewpointF: 500

Viewer.ShowOctotreeMap: 0
Viewer.Showobject: 0
Viewer.ShowPoints: 0
Viewer.ShowAllPointcloud: 0

DisplayDetect: 0
#--------------------------------------------------------------------------------------------
# PointCloudMapping Parameters
#--------------------------------------------------------------------------------------------
PointCloudMapping.Resolution: 0.05

#--------------------------------------------------------------------------------------------
# octomap Parameters
#--------------------------------------------------------------------------------------------
octoMap.res: 0.05

#--------------------------------------------------------------------------------------------
# Dynamic point
#--------------------------------------------------------------------------------------------
Dynamic.flow: 50.0

